# Generated by Django 2.2.4 on 2020-03-22 13:38

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='quiz_bonuss',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
