# Generated by Django 2.2.4 on 2020-03-22 13:41

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_player_quiz_bonuss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='quiz_bonuss',
        ),
        migrations.AddField(
            model_name='player',
            name='quiz_bonus',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
