# Generated by Django 2.2.4 on 2020-03-22 13:42

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200322_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='quiz_bonus',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
