# Generated by Django 2.2.4 on 2020-03-24 06:03

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200322_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='practice_contribution',
        ),
        migrations.AddField(
            model_name='player',
            name='practice_contrib1',
            field=otree.db.models.CurrencyField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='practice_contrib2',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
