# Generated by Django 2.2.4 on 2020-04-08 04:54

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('bot_contributions', otree.db.models.LongStringField(null=True)),
                ('bot_round_contrib_total', otree.db.models.IntegerField(null=True)),
                ('bot_round_avg', otree.db.models.FloatField(null=True)),
                ('group_round_contrib_total', otree.db.models.IntegerField(null=True)),
                ('group_round_witheld_total', otree.db.models.IntegerField(null=True)),
                ('group_round_avg', otree.db.models.FloatField(null=True)),
                ('game_total_contrib', otree.db.models.IntegerField(null=True)),
                ('group_game_bonus', otree.db.models.IntegerField(null=True)),
                ('carbonfund_total', otree.db.models.IntegerField(null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_group', to='otree.Session')),
            ],
            options={
                'db_table': 'game_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'game_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('round', otree.db.models.StringField(max_length=10000, null=True)),
                ('contributed', otree.db.models.IntegerField(null=True)),
                ('withheld', otree.db.models.IntegerField(null=True)),
                ('total_contributed', otree.db.models.IntegerField(null=True)),
                ('total_witheld', otree.db.models.IntegerField(null=True)),
                ('contributions', otree.db.models.LongStringField(null=True)),
                ('player_game_bonus', otree.db.models.FloatField(null=True)),
                ('quiz_bonus', otree.db.models.IntegerField(null=True)),
                ('total_payoff', otree.db.models.CurrencyField(null=True)),
                ('game_result', otree.db.models.LongStringField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Subsession')),
            ],
            options={
                'db_table': 'game_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Subsession'),
        ),
    ]
