# Generated by Django 2.2.4 on 2020-03-22 13:07

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='carbonFund',
        ),
        migrations.AddField(
            model_name='group',
            name='carbonfund_total',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
