# Generated by Django 2.2.4 on 2020-03-22 13:07

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200322_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='carbonfund_total',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
