# Generated by Django 2.2.4 on 2020-03-22 15:36

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200322_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_round_avg',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
