# Generated by Django 2.2.4 on 2020-03-22 16:29

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_group_group_round_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='bot_round_avg',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
