# Generated by Django 2.2.4 on 2020-03-22 16:37

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_group_bot_round_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='bot_round_total',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='group_round_total',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
