#!/bin/bash


BASE_PATH="$(npm prefix)"
[[ -f "${BASE_PATH}/./.npmrc" ]] && . ${BASE_PATH}/./.npmrc

OTREE_SERVER_VERBOSITY=2
APP_DIR="app"


__run__() {

  cd "${BASE_PATH}/app" && \
  /usr/local/bin/otree devserver --force-color --verbosity="${OTREE_SERVER_VERBOSITY}"

  google-chrome http://localhost:8000
}

export PYTHONPATH=/usr/bin/python3.7 \
  && __run__
