#!/bin/bash


OTREE_SERVER_VERBOSITY=2
APP_DIR="app"

__run__() {
  /usr/local/bin/otree devserver --force-color --verbosity="${OTREE_SERVER_VERBOSITY}"

  google-chrome http://localhost:8000
}

cd "${APP_DIR}"

export PYTHONPATH=/usr/bin/python3.7 \
  && __run__
