# Generated by Django 2.2.4 on 2020-03-22 13:54

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_game_group', to='otree.Session')),
            ],
            options={
                'db_table': 'post_game_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_game_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'post_game_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('survey_consent', otree.db.models.BooleanField(choices=[[True, 'Yes, I give my permission for the researchers to use my data.'], [False, 'No, I do not give permission for the researchers to use my data. Please discard the data you obtained from me.']], null=True, verbose_name='')),
                ('s1a1', otree.db.models.StringField(max_length=10000, null=True, verbose_name='What were you trying to do in the game (in other words: what were your goals or objectives)?')),
                ('s1a2', otree.db.models.BooleanField(choices=[[True, 'Yes'], [False, 'No']], null=True, verbose_name='Did you achieve your objectives?')),
                ('s1a3', otree.db.models.StringField(max_length=10000, null=True, verbose_name='What information guided your decisions throughout the game?')),
                ('s1a4', otree.db.models.StringField(max_length=10000, null=True, verbose_name='What were the other members of your group trying to do (what were their objectives)?')),
                ('s1a5', otree.db.models.StringField(max_length=10000, null=True, verbose_name='What was the scope of this experiment (in other words, what were the experimenters trying to discover)?')),
                ('s1b1', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='This experiment requires a lot of concentration.')),
                ('s1b2', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='The rules of the game were explained clearly.')),
                ('s1b3', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='In this experiment one must try to work together with others to have everyone end up with more money.')),
                ('s1b4', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='In this experiment, the air pollution impact was more important to me than the financial incentive for             meeting the group conservation goal (i.e. the bonus).')),
                ('s1b5', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="In this experiment, everyone's earnings depend on the decisions of all members of the group.")),
                ('s1c1', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='My past contributions to the group conservation account.')),
                ('s1c2', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="Others' average contributions to the group conservation account.")),
                ('s1c3', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Total contributions to the group conservation account from all 25 players.')),
                ('s1c4', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Cumulative percentage of the group goal achieved.')),
                ('s1c5', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='The environmental benefits of conservation (the donation to remove air pollution).')),
                ('s2a0', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='I like to help other people')),
                ('s2a1', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='I like to share my ideas and materials with others')),
                ('s2a2', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='People learn lots of important things from each other')),
                ('s2a3', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='I work to get better than others')),
                ('s2a4', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='I like to be the best at what I do')),
                ('s2a5', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='I like the challenge of seeing who is best')),
                ('s2a6', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name="I don't like working with others")),
                ('s2a7', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='It bothers me when I have to work with others')),
                ('s2a8', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='I work better when I do it all myself')),
                ('s3a0', otree.db.models.IntegerField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, '']], null=True, verbose_name='Plants')),
                ('s3a1', otree.db.models.IntegerField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, '']], null=True, verbose_name='Marine life')),
                ('s3a2', otree.db.models.IntegerField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, '']], null=True, verbose_name='Birds')),
                ('s3a3', otree.db.models.IntegerField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, '']], null=True, verbose_name='Animals')),
                ('s3a4', otree.db.models.IntegerField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, '']], null=True, verbose_name='My prosperity')),
                ('s3a5', otree.db.models.IntegerField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, '']], null=True, verbose_name='My lifestyle')),
                ('s3a6', otree.db.models.IntegerField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, '']], null=True, verbose_name='My health')),
                ('s3a7', otree.db.models.IntegerField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, '']], null=True, verbose_name='My future')),
                ('s3a8', otree.db.models.IntegerField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, '']], null=True, verbose_name='People in my community')),
                ('s3a9', otree.db.models.IntegerField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, '']], null=True, verbose_name='The human race')),
                ('s3a10', otree.db.models.IntegerField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, '']], null=True, verbose_name='Children')),
                ('s4a1', otree.db.models.IntegerField(null=True, verbose_name='What is your year of birth?')),
                ('s4a2', otree.db.models.IntegerField(choices=[[1, 'Male'], [2, 'Female'], [3, 'Other']], null=True, verbose_name='What is your gender?')),
                ('s4a3', otree.db.models.IntegerField(choices=[[1, 'American Indian/Alaska Native'], [2, 'Asian'], [3, 'Black or African-American'], [4, 'Native Hawaiian/Pacific Islander'], [5, 'White'], [6, 'Other']], null=True, verbose_name='What term best describes your racial identity?')),
                ('s4a4', otree.db.models.IntegerField(choices=[[1, 'Full time employed'], [2, 'Full time student'], [3, 'Part time employed'], [4, 'Part time student'], [5, 'Other']], null=True, verbose_name='What is your economic status?')),
                ('s4a5', otree.db.models.IntegerField(choices=[[1, 'None'], [2, '1-2 previous'], [3, '3-5 previous'], [4, 'More than 5 previous']], null=True, verbose_name='How many multi-player game experiments like the one you just played have you             participated in before this one?')),
                ('s4a6', otree.db.models.BooleanField(choices=[[True, 'Yes'], [False, 'No']], null=True, verbose_name='Are your responses reliable enough for us to include them in our academic             research that will have real implications on energy and housing community policy making?')),
                ('s4a7', otree.db.models.IntegerField(choices=[[1, 'Democrat'], [2, 'Republican'], [3, 'Independent'], [4, 'Other']], null=True, verbose_name='Which political party do you most identify with?')),
                ('s4a8', otree.db.models.IntegerField(null=True, verbose_name='How many years have you lived in the US?')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post_game.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_game_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_game_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_game.Subsession')),
            ],
            options={
                'db_table': 'post_game_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_game.Subsession'),
        ),
    ]
